/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.jsharkey.grouphome;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int grid_text=0x7f050000;
    }
    public static final class drawable {
        public static final int black_bar=0x7f020000;
        public static final int focused_application_background=0x7f020001;
        public static final int grid_selector=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int pressed_application_background=0x7f020004;
        public static final int settings_header=0x7f020005;
        public static final int settings_header_list=0x7f020006;
        public static final int settings_header_raw=0x7f020007;
    }
    public static final class layout {
        public static final int act_launch=0x7f030000;
        public static final int item_entry=0x7f030001;
        public static final int item_header=0x7f030002;
        public static final int item_row=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
