/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.jsharkey.oilcan;

public final class R {
    public static final class array {
        public static final int list_examples=0x7f060000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int dialog_full_dark=0x7f020000;
        public static final int ic_menu_bookmark=0x7f020001;
        public static final int ic_menu_goto=0x7f020002;
        public static final int ic_menu_refresh=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int scrollbar_handle_accelerated_anim2=0x7f020005;
    }
    public static final class id {
        public static final int browse_webview=0x7f080000;
        public static final int browse_zoom=0x7f080001;
        public static final int label=0x7f080003;
        public static final int name=0x7f080002;
        public static final int number=0x7f080004;
        public static final int script_descrip=0x7f080006;
        public static final int script_enabled=0x7f080007;
        public static final int script_title=0x7f080005;
    }
    public static final class layout {
        public static final int act_browse=0x7f030000;
        public static final int act_scriptlist=0x7f030001;
        public static final int contacts_list_content=0x7f030002;
        public static final int contacts_list_item=0x7f030003;
        public static final int item_script=0x7f030004;
    }
    public static final class raw {
        public static final int email=0x7f050000;
        public static final int halfscan=0x7f050001;
        public static final int json2=0x7f050002;
        public static final int sharedigg=0x7f050003;
        public static final int slashdot=0x7f050004;
        public static final int userscripts=0x7f050005;
        public static final int wikipedia=0x7f050006;
    }
    public static final class string {
        public static final int app_desc=0x7f070001;
        public static final int app_email=0x7f070003;
        public static final int app_name=0x7f070000;
        public static final int app_scripts=0x7f070002;
        public static final int browse_example=0x7f07000a;
        public static final int browse_example_title=0x7f07000b;
        public static final int browse_gotourl=0x7f070007;
        public static final int browse_manage=0x7f070009;
        public static final int browse_nointent=0x7f07000c;
        public static final int browse_refresh=0x7f070008;
        public static final int browse_title=0x7f07000d;
        public static final int install_message=0x7f07000f;
        public static final int install_title=0x7f07000e;
        public static final int manage_delete=0x7f070013;
        public static final int manage_empty=0x7f070012;
        public static final int manage_find=0x7f070010;
        public static final int manage_import=0x7f070011;
        public static final int manage_import_fail=0x7f070017;
        public static final int manage_import_success=0x7f070016;
        public static final int manage_pick=0x7f070014;
        public static final int manage_pick_error=0x7f070015;
        public static final int search_button_text=0x7f070006;
        public static final int search_hint=0x7f070005;
        public static final int search_label=0x7f070004;
    }
    public static final class xml {
        public static final int searchable=0x7f040000;
    }
}
